# Generated by Django 6.0.1 on 2026-02-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short description for page lists'),
        ),
    ]
