# Generated by Django 6.0.1 on 2026-02-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_page_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='address',
            field=models.CharField(blank=True, help_text='Address for contact page', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for contact page', max_length=254),
        ),
        migrations.AddField(
            model_name='page',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for contact page', max_length=50),
        ),
    ]
