# Generated by Django 6.0.1 on 2026-02-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_eventgallery_classsection_excerpt_classsection_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
